server:
  port: 8081
  servlet:
    context-path: /cloud

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    schemas: cloud

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

  banner:
    location: classpath:banner.txt

logging:
  level:
    ru:
      netology:
        diplomacloudapi: info
    org:
      apache:
        tomcat: warn
      hibernate: error
      springframework:
        web: warn
  file:
    name: logs/cloud.log

my:
  file:
    directory: Files_uploaded
  jwt:
    secret-key: 71337336763979244226452948404D635166546A576E5A7234753777217A2543
    expiration-term: 86_400_000 #1 day
  auth-header: Auth-Token #for FRONT
  #  auth-header: Authorization #for POSTMAN
  cors:
    allowed-origins: http://localhost:8080
